#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [users, admin]
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrSv+lPkHS3L/Fwh8x1Vru4gqOhXaAH+GOfM9xQGRZkAVvm7q++idhqN2cSZfK2uXd0RI7DAywyWRtii+JyQnMW1odkRCy3+e5ddR4HnjUdaWAfo3JkhBt88+cABq06FdrlWr0Bw1pLZAl/83mh2CiQAJ/4J4NcHduVuKjNTHYaGKW31IcKBaQRu9zFysWgiYatR4/S7x92EpvQAya3YwjEkud2+WVm3iDgGpQjFbzznK2OnqbXomSzS1R+Z1jAxo9Ld9lTbYc1BtI5BIxfrjyPiV++feyMCTPHtiCfUD3k1aqRb5Crib6i4fc2gQQk8iilPm52YkV13FYSWwEagNh aws-key-lis
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key-NUY

ssh_pwauth: false
disable_root: true

package_update: true
packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer

write_files:
  - path: /var/www/html/info.php
    content: |
      <?php phpinfo(); ?>

  - path: /var/www/html/db.php
    content: |
      <?php
      $servername = "172.31.19.110";
      $username = "admin";
      $password = "lisa123";
      $dbname = "mysql";
      $conn = new mysqli($servername, $username, $password, $dbname);
      if ($conn->connect_error) { die("Connection failed: " . $conn->connect_error); }
      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
        echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
      }
      ?>

runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
