#cloud-config

users:
  - name: ubuntu
    groups: [users, admin]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsTbOWQi+eeflo52Y2Kuie0xAzQUrXdjuSeG0cmEm4XGHX7GSqbDctfmfmpkDxB8vv9xL1Q0DzGfeKokUskUYEDPMZFGdaWdYoDAUCM7rGsLOtZv+gsvuN5u1/1OrjcvaXhK9xMDrrFyQAd3uOh0URQHjiwFne6WE/5blLcO5RhvAbqo1itdL+wm9gMtmjEEUiWtsxe+Hi34kDBGFTSt/ajwOv3sDTHzS+9EitBE9h0U8nYUdIQchwE4sg6Lg4jXmA3Ti3sGU7mzKpPQ9FJAounSf06FQ98xcMoqINNVfG13IR/ZJfnyyvjLGO9hYKY/quatr/feWkYC0G/2OZleXr aws-key-lis
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj2+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflflR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key-NUY

ssh_pwauth: false
disable_root: false

package_update: true

packages:
  - mariadb-server

runcmd:
  - mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'lisa123' WITH GRANT OPTION;"
  - sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - systemctl restart mariadb.service
